"""second

Revision ID: 304381161fb6
Revises: 9bd3d9f09cd3
Create Date: 2020-05-24 01:50:55.292924

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '304381161fb6'
down_revision = '9bd3d9f09cd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pictures',
    sa.Column('pic_id', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('colour_hex', sa.Binary(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('sub_category', sa.String(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('NSFW', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('service', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('pic_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('permissions', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('pics_uploaded', sa.Integer(), nullable=True),
    sa.Column('pics_accepted', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('register_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_table('Users')
    op.drop_table('Pictures')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Pictures',
    sa.Column('pic_id', sa.INTEGER(), server_default=sa.text('nextval(\'"Pictures_pic_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('width', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('colour_hex', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sub_category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('NSFW', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('service', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('pic_id', name='Pictures_pkey')
    )
    op.create_table('Users',
    sa.Column('user_id', sa.INTEGER(), server_default=sa.text('nextval(\'"Users_user_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('nickname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('permissions', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('pics_uploaded', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pics_accepted', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('register_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='Users_pkey')
    )
    op.drop_table('users')
    op.drop_table('pictures')
    # ### end Alembic commands ###
