"""fistssas

Revision ID: 4be18a10da36
Revises: 
Create Date: 2020-06-24 03:50:56.292516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4be18a10da36'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('category_name')
    )
    op.create_table('seen_pictures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('tags',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('tag_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('tag_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('pics_uploaded', sa.Integer(), nullable=True),
    sa.Column('register_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('admins',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tg_state', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.create_table('moderators',
    sa.Column('mod_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pics_accepted', sa.Integer(), nullable=True),
    sa.Column('json_review', sa.JSON(), nullable=True),
    sa.Column('tg_state', sa.Integer(), nullable=True),
    sa.Column('last_message', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('mod_id')
    )
    op.create_table('sub_categories',
    sa.Column('sub_category_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('sub_category_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.PrimaryKeyConstraint('sub_category_id'),
    sa.UniqueConstraint('sub_category_name')
    )
    op.create_table('pictures',
    sa.Column('pic_id', sa.Integer(), nullable=False),
    sa.Column('uploader_id', sa.Integer(), nullable=True),
    sa.Column('mod_review_id', sa.Integer(), nullable=True),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('colours', sa.ARRAY(sa.Binary()), nullable=True),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.Column('sub_category', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['categories.category_id'], ),
    sa.ForeignKeyConstraint(['mod_review_id'], ['moderators.mod_id'], ),
    sa.ForeignKeyConstraint(['sub_category'], ['sub_categories.sub_category_id'], ),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('pic_id')
    )
    op.create_table('rejected_pictures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mod_id', sa.Integer(), nullable=True),
    sa.Column('uploader', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['mod_id'], ['moderators.mod_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assosiation',
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('pic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pic_id'], ['pictures.pic_id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.tag_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assosiation')
    op.drop_table('rejected_pictures')
    op.drop_table('pictures')
    op.drop_table('sub_categories')
    op.drop_table('moderators')
    op.drop_table('admins')
    op.drop_table('users')
    op.drop_table('tags')
    op.drop_table('seen_pictures')
    op.drop_table('categories')
    # ### end Alembic commands ###
