"""first version

Revision ID: 9bd3d9f09cd3
Revises: 
Create Date: 2020-05-24 00:30:46.928653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bd3d9f09cd3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Pictures',
    sa.Column('pic_id', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('colour_hex', sa.Binary(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('sub_category', sa.String(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('NSFW', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('service', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('pic_id')
    )
    op.create_table('Users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('permissions', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('pics_uploaded', sa.Integer(), nullable=True),
    sa.Column('pics_accepted', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('register_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users')
    op.drop_table('Pictures')
    # ### end Alembic commands ###
