# This is a basic workflow to help you get started with Actions

name: Update_all_docker_dev_images_with_fresh_lib
on:
  push:
    branches: [ dev ]
         
jobs:
  dispatch:
    strategy:
      matrix:
        repo: ['walld-app/grab_pexels', 'walld-app/walld_insert_pic', 'walld-app/api.walld.net', 'walld-app/walld_tg_bot']
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS }}
          repository: ${{ matrix.repo }}
          event-type: dev-db-updated

